export const PricingData = [
  // Website Packages
  {
    id: 1,
    category: "website",
    plan_name: "Basic Website Package",
    plan_details: "5-Page Website with Mobile-Friendly Design",
    price: "350",
    time: "One-time payment",
    link: "https://link.omnidigitalsolutions.ai/payment-link/669a37758dc91229a8bfb9d7",
    features: [
      "Mobile-Friendly Design",
      "Basic SEO Setup",
      "Contact Form",
      "Free Lifetime Hosting",
      "Social Media Integration",
      "Security Features: SSL Certificate",
      "Google Analytics",
      "Easy Content Management",
    ],
    benefit: "Get started with a fast, mobile-friendly website designed to attract and convert visitors into paying customers. Perfect for establishing your brand online with essential features.",
  },
  {
    id: 2,
    category: "website",
    plan_name: "Standard Website Package",
    plan_details: "7-Page Website with Enhanced Features",
    price: "525",
    time: "One-time payment",
    link: "https://link.omnidigitalsolutions.ai/payment-link/669a51008dc9123a8cbfb9e8",
    features: [
      "Responsive Design",
      "Advanced SEO Optimization",
      "Contact Forms & Lead Generation",
      "Free Hosting (1 Year)",
      "E-commerce Integration",
      "Enhanced Security with SSL",
      "Social Media Integration",
      "Analytics Dashboard",
      "Fast Loading Time",
      "Integrated Appointment Scheduling",
      "Client Portal Access",
    ],
    benefit: "Ideal for growing businesses, this package ensures your website works harder to generate leads and sales with advanced SEO and e-commerce features.",
  },
  {
    id: 3,
    category: "website",
    plan_name: "Enhanced Website Package",
    plan_details: "10-Page Website with Custom Design",
    price: "950",
    time: "One-time payment",
    link: "https://link.omnidigitalsolutions.ai/payment-link/669a52bb3fce18773ab4bf9e",
    features: [
      "Custom Responsive Design",
      "Comprehensive SEO",
      "Advanced Contact Forms & Lead Generation",
      "Premium Hosting & Domain Management",
      "E-commerce Excellence with Custom Features",
      "Top-tier Security with Advanced SSL",
      "Social Media Integration",
      "Advanced Analytics Dashboard",
      "Ongoing Support & Maintenance",
      "Integrated Marketing Automation",
      "Customizable Client Portal",
    ],
    benefit: "This package is perfect for businesses needing a tailored, high-performance website that maximizes conversions and keeps your online presence secure and scalable.",
  },

  // App Services
  {
    id: 4,
    category: "app",
    plan_name: "Basic App Package",
    plan_details: "Basic Features for Mobile Apps",
    price: "700",
    time: "One-time payment",
    link: "#app-basic",
    features: [
      "User Authentication",
      "Push Notifications",
      "Basic UI/UX Design",
    ],
    benefit: "Launch your mobile app with core features like authentication and push notifications that help engage your users while maintaining a simple, easy-to-navigate design.",
  },
  {
    id: 5,
    category: "app",
    plan_name: "Standard App Package",
    plan_details: "Advanced Features for Mobile Apps",
    price: "1200",
    time: "One-time payment",
    link: "#app-standard",
    features: [
      "Social Media Integration",
      "Custom UI/UX Design",
      "API Integration",
      "Push Notifications",
      "User Authentication",
      "Integrated Analytics Dashboard",
    ],
    benefit: "Perfect for scaling businesses, this package provides a custom mobile experience, seamless social media integration, and valuable user insights to drive growth.",
  },
  {
    id: 6,
    category: "app",
    plan_name: "Pro App Package",
    plan_details: "Comprehensive App Development",
    price: "2500",
    time: "One-time payment",
    link: "#app-pro",
    features: [
      "Custom App Development",
      "In-depth User Analytics",
      "Monetization Features",
      "High-Level Security Protocols",
      "Social Media Integration",
      "Real-Time Data Sync",
    ],
    benefit: "For businesses ready to dominate the app market, this package offers fully customizable features, powerful security, and monetization options to maximize revenue and user engagement.",
  },

  // Ads Services
  {
    id: 7,
    category: "ads",
    plan_name: "Basic Ads Package",
    plan_details: "Essential Ads Management",
    price: "300",
    time: "Monthly",
    link: "#ads-basic",
    features: [
      "Ad Creation & Management",
      "Basic Targeting Options",
      "Monthly Performance Reports",
      "Ad Budget Monitoring",
    ],
    benefit: "Start advertising with confidence using targeted ads to attract your ideal audience, with monthly reports to ensure you’re seeing a solid return on investment.",
  },
  {
    id: 8,
    category: "ads",
    plan_name: "Standard Ads Package",
    plan_details: "Enhanced Ads Management with Optimization",
    price: "600",
    time: "Monthly",
    link: "#ads-standard",
    features: [
      "Advanced Targeting Options",
      "A/B Testing of Ads",
      "Weekly Performance Reports",
      "Ad Budget Optimization",
    ],
    benefit: "Boost your ad performance with A/B testing and advanced targeting, ensuring your ad spend generates the best possible results for your business growth.",
  },
  {
    id: 9,
    category: "ads",
    plan_name: "Premium Ads Package",
    plan_details: "Comprehensive Ads Management Strategy",
    price: "1200",
    time: "Monthly",
    link: "#ads-premium",
    features: [
      "Custom Ad Strategies",
      "In-depth Audience Research",
      "Daily Performance Monitoring",
      "Cross-Platform Ad Management",
      "Dedicated Account Manager",
    ],
    benefit: "Unlock the full potential of your ads with custom strategies, cross-platform management, and a dedicated account manager to ensure your campaigns consistently perform at their peak.",
  },

  // Business Autopilot
  {
    id: 10,
    category: "business",
    plan_name: "Business Autopilot Basic",
    plan_details: "Automate Key Business Functions",
    price: "450",
    time: "Monthly",
    link: "#business-basic",
    features: [
      "Automated Email Campaigns",
      "Basic CRM Integration",
      "Lead Scoring & Tracking",
      "Monthly Analytics Reports",
    ],
    benefit: "Streamline your business operations with automated email campaigns and CRM integration to keep track of leads and boost productivity without manual effort.",
  },
  {
    id: 11,
    category: "business",
    plan_name: "Business Autopilot Standard",
    plan_details: "Enhanced Business Automation Solutions",
    price: "900",
    time: "Monthly",
    link: "#business-standard",
    features: [
      "Advanced CRM Integration",
      "Lead Generation Tools",
      "Automated Workflows",
      "Weekly Performance Reports",
    ],
    benefit: "Get the tools you need to automate your business processes, generate leads, and track your performance on a weekly basis with no hassle.",
  },
  {
    id: 12,
    category: "business",
    plan_name: "Business Autopilot Premium",
    plan_details: "Comprehensive Business Automation Package",
    price: "1500",
    time: "Monthly",
    link: "#business-premium",
    features: [
      "Custom Automation Solutions",
      "Dedicated Support",
      "In-depth Analytics",
      "Integration with Third-party Apps",
    ],
    benefit: "Enjoy complete business automation tailored to your needs, with dedicated support and integration with third-party apps to ensure your business runs smoothly and efficiently.",
  },
];
